// US States mapping: Chinese name -> English name
export const US_STATES: Record<string, string> = {
  阿拉巴马州: 'Alabama',
  阿拉斯加州: 'Alaska',
  亚利桑那州: 'Arizona',
  阿肯色州: 'Arkansas',
  加利福尼亚州: 'California',
  加州: 'California',
  科罗拉多州: 'Colorado',
  康涅狄格州: 'Connecticut',
  特拉华州: 'Delaware',
  佛罗里达州: 'Florida',
  佐治亚州: 'Georgia',
  夏威夷州: 'Hawaii',
  爱达荷州: 'Idaho',
  伊利诺伊州: 'Illinois',
  印第安纳州: 'Indiana',
  艾奥瓦州: 'Iowa',
  堪萨斯州: 'Kansas',
  肯塔基州: 'Kentucky',
  路易斯安那州: 'Louisiana',
  缅因州: 'Maine',
  马里兰州: 'Maryland',
  马萨诸塞州: 'Massachusetts',
  密歇根州: 'Michigan',
  明尼苏达州: 'Minnesota',
  密西西比州: 'Mississippi',
  密苏里州: 'Missouri',
  蒙大拿州: 'Montana',
  内布拉斯加州: 'Nebraska',
  内华达州: 'Nevada',
  新罕布什尔州: 'New Hampshire',
  新泽西州: 'New Jersey',
  新墨西哥州: 'New Mexico',
  纽约州: 'New York',
  北卡罗来纳州: 'North Carolina',
  北卡羅萊那州: 'North Carolina', // Traditional Chinese
  北达科他州: 'North Dakota',
  俄亥俄州: 'Ohio',
  俄克拉荷马州: 'Oklahoma',
  俄勒冈州: 'Oregon',
  宾夕法尼亚州: 'Pennsylvania',
  罗得岛州: 'Rhode Island',
  南卡罗来纳州: 'South Carolina',
  南达科他州: 'South Dakota',
  田纳西州: 'Tennessee',
  得克萨斯州: 'Texas',
  德克萨斯州: 'Texas',
  犹他州: 'Utah',
  佛蒙特州: 'Vermont',
  弗吉尼亚州: 'Virginia',
  华盛顿州: 'Washington',
  西弗吉尼亚州: 'West Virginia',
  威斯康星州: 'Wisconsin',
  怀俄明州: 'Wyoming',
  哥伦比亚特区: 'District of Columbia',
  華盛頓特區: 'District of Columbia', // Traditional Chinese
  波多黎各: 'Puerto Rico',
};

// Major US cities mapping: Chinese name -> English name
export const US_CITIES: Record<string, string> = {
  // Major metros
  纽约: 'New York',
  洛杉矶: 'Los Angeles',
  芝加哥: 'Chicago',
  休斯顿: 'Houston',
  凤凰城: 'Phoenix',
  费城: 'Philadelphia',
  圣安东尼奥: 'San Antonio',
  圣地亚哥: 'San Diego',
  达拉斯: 'Dallas',
  圣何塞: 'San Jose',
  奥斯汀: 'Austin',
  杰克逊维尔: 'Jacksonville',
  旧金山: 'San Francisco',
  哥伦布: 'Columbus',
  沃思堡: 'Fort Worth',
  印第安纳波利斯: 'Indianapolis',
  夏洛特: 'Charlotte',
  西雅图: 'Seattle',
  丹佛: 'Denver',
  华盛顿: 'Washington',
  華盛頓: 'Washington', // Traditional Chinese
  波士顿: 'Boston',
  埃尔帕索: 'El Paso',
  底特律: 'Detroit',
  纳什维尔: 'Nashville',
  波特兰: 'Portland',
  孟菲斯: 'Memphis',
  俄克拉荷马城: 'Oklahoma City',
  拉斯维加斯: 'Las Vegas',
  路易斯维尔: 'Louisville',
  巴尔的摩: 'Baltimore',
  密尔沃基: 'Milwaukee',
  阿尔伯克基: 'Albuquerque',
  图森: 'Tucson',
  弗雷斯诺: 'Fresno',
  萨克拉门托: 'Sacramento',
  堪萨斯城: 'Kansas City',
  梅萨: 'Mesa',
  弗吉尼亚海滩: 'Virginia Beach',
  亚特兰大: 'Atlanta',
  长滩: 'Long Beach',
  科罗拉多斯普林斯: 'Colorado Springs',
  罗利: 'Raleigh',
  羅里: 'Raleigh', // Traditional Chinese variant
  羅利: 'Raleigh', // Traditional Chinese variant
  迈阿密: 'Miami',
  奥克兰: 'Oakland',
  明尼阿波利斯: 'Minneapolis',
  塔尔萨: 'Tulsa',
  阿灵顿: 'Arlington',
  新奥尔良: 'New Orleans',
};

// City to state mapping (English names)
export const CITY_TO_STATE: Record<string, string> = {
  'New York': 'New York',
  'Los Angeles': 'California',
  Chicago: 'Illinois',
  Houston: 'Texas',
  Phoenix: 'Arizona',
  Philadelphia: 'Pennsylvania',
  'San Antonio': 'Texas',
  'San Diego': 'California',
  Dallas: 'Texas',
  'San Jose': 'California',
  Austin: 'Texas',
  Jacksonville: 'Florida',
  'San Francisco': 'California',
  Columbus: 'Ohio',
  'Fort Worth': 'Texas',
  Indianapolis: 'Indiana',
  Charlotte: 'North Carolina',
  Seattle: 'Washington',
  Denver: 'Colorado',
  Washington: 'District of Columbia',
  Boston: 'Massachusetts',
  'El Paso': 'Texas',
  Detroit: 'Michigan',
  Nashville: 'Tennessee',
  Portland: 'Oregon',
  Memphis: 'Tennessee',
  'Oklahoma City': 'Oklahoma',
  'Las Vegas': 'Nevada',
  Louisville: 'Kentucky',
  Baltimore: 'Maryland',
  Milwaukee: 'Wisconsin',
  Albuquerque: 'New Mexico',
  Tucson: 'Arizona',
  Fresno: 'California',
  Sacramento: 'California',
  'Kansas City': 'Missouri',
  Mesa: 'Arizona',
  'Virginia Beach': 'Virginia',
  Atlanta: 'Georgia',
  'Long Beach': 'California',
  'Colorado Springs': 'Colorado',
  Raleigh: 'North Carolina',
  Miami: 'Florida',
  Oakland: 'California',
  Minneapolis: 'Minnesota',
  Tulsa: 'Oklahoma',
  Arlington: 'Texas',
  'New Orleans': 'Louisiana',
};
